//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTGSalvationScraper.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AddReprints {
            get {
                return ((bool)(this["AddReprints"]));
            }
            set {
                this["AddReprints"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultCardFileLocation {
            get {
                return ((string)(this["DefaultCardFileLocation"]));
            }
            set {
                this["DefaultCardFileLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HKEY_CURRENT_USER\\Software\\Cockatrice\\Cockatrice\\paths")]
        public string CockatriceRegistryKey {
            get {
                return ((string)(this["CockatriceRegistryKey"]));
            }
            set {
                this["CockatriceRegistryKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("carddatabase")]
        public string CockatriceRegistryValue {
            get {
                return ((string)(this["CockatriceRegistryValue"]));
            }
            set {
                this["CockatriceRegistryValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>cards.xml</string>\r\n  <string>card.xml</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DefaultCardFileNames {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DefaultCardFileNames"]));
            }
            set {
                this["DefaultCardFileNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M15")]
        public string SetName {
            get {
                return ((string)(this["SetName"]));
            }
            set {
                this["SetName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M15")]
        public string LongSetName {
            get {
                return ((string)(this["LongSetName"]));
            }
            set {
                this["LongSetName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.mtgsalvation.com/spoilers/141-magic-2015")]
        public string MTGSalvationUrl {
            get {
                return ((string)(this["MTGSalvationUrl"]));
            }
            set {
                this["MTGSalvationUrl"] = value;
            }
        }
    }
}
